# Site settings
title: pickaxe's blog
email: tzp_1991@qq.com
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://tianzhipeng.gitee.io" # the base hostname & protocol for your site
permalink: /:year/:month/:day/:title.html

# Build settings
markdown: kramdown

asciidoctor: {}
asciidoc: {}